spring:
  application:
    name: hhplus-clean-architecture
  profiles:
    active: dev
    group:
      dev:
        - common
        - dev
      test:
        - common
        - test

---

spring:
  jpa:
    hibernate:
      ddl-auto: common
      jpa:
        properties:
          hibernate:
            show-sql: true
            format-sql: true
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hhplus_clean_architecture?characterEncoding=utf8&useUnicode=true
    username: hhplus
    password: hhplus1234
    jpa:
      properties:
        hibernate:
            ddl-auto: validate
            dialect: org.hibernate.dialect.MySQL8Dialect
  server:
    port: 8080

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_UPPER=false
    username: sa
    password:
    jpa:
      properties:
        hibernate:
            ddl-auto: create-drop
            dialect: org.hibernate.dialect.H2Dialect
  server:
    port: 8081