spring:
  application:
    name: hhplus-clean-architecture
  profiles:
    active: dev
    group:
      dev:
        - dev
      test:
        - test

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hhplus_clean_architecture?characterEncoding=utf8&useUnicode=true
    username: hhplus
    password: hhplus1234
    jpa:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
        format-sql: true
  server:
    port: 8080

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: test
    password: test1234
    jpa:
      hibernate:
        ddl-auto: create-drop
        dialect: org.hibernate.dialect.H2Dialect
        show-sql: true
        format-sql: true
  server:
    port: 8081